version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - DB_URI=postgres://ahmed:ahmed123@db:5432/users
      - JWT_SECRET=your-secret-key
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ahmed123
      POSTGRES_DB: users
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
